### ISSUE TITLE
`StringWriter` unsupported in `process`

### ISSUE THREAD

**Issue by helins** [babashka/process#104]
It seems passing a `StringWriter` as `:out` or `:err` does not have an effect.

E.g. Provided file is empty after running this:

```clojure
(deref (babashka.process/process ["echo" "foo"]
                                 {:out (java.io.FileWriter. "/tmp/foo")}))
```

**Comment by borkdude** [comment]
It seems you have to close `FileWriter` still:

```
(with-open [fw (java.io.FileWriter. "/tmp/foo.txt")]
  @(babashka.process/process {:out fw}
                             "echo" "foo"
                             ))
```

The same issue can happen with `(io/copy .. (java.io.FileWriter.))` without wrapping it with `with-open`.
