### ISSUE TITLE
Consider supporting redirecting stderr to stdout

### ISSUE THREAD

**Issue by lread** [babashka/process#113]
## Problem
Babashka/process currently easily supports controlling destinations for stderr and stdout.

But... it does not currently easily support merging stderr and stdout to a single output stream.
This can be very useful when you don't care about stderr vs stdout but do care about capturing all output in the order it occurs over time.

## JDK Support
[`ProcessBuilder` includes `redirectErrorStream`](https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html#redirectErrorStream--).
Docs on its effect are found in the [`ProcessBuilder` class JavaDoc](https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html).

## Explore Current Behaviour
Using the current release 0.4.16 of babashka/process, and a wee bb `outerr.clj` script to explore:
```Clojure
(println "I am written to stdout")

(binding [*out* *err*]
  (println "I am written to stderr"))
```

Today we can easily get stderr and stdout separately:
```Clojure
(require '[babashka.process :as p])

(-> (p/shell {:out :string :err :string} "bb outerr.clj")
    (select-keys [:out :err]))
;; => {:out "I am written to stdout\n", :err "I am written to stderr\n"}
```

But merging stderr to stdout, while possible, is a bit lower level than it could be:
```Clojure
(let [pb (p/pb {:out :string} "bb outerr.clj")
      pb-obj (:pb pb)]
  (.redirectErrorStream pb-obj true)
  (:out @(p/start pb)))
;; => "I am written to stdout\nI am written to stderr\n"
```

## Proposed API change
@borkdude and I hashed out syntax on Slack and he came up with the succinct `:err :out`.
Nice!

With this new syntax, the lower-level example above could be re-expressed like so:
```Clojure
(-> (p/shell {:out :string :err :out} "bb outerr.clj")
    :out)
;; => "I am written to stdout\nI am written to stderr\n"
```

The `:err :out` syntax will be applicable to all API fns where `:err` is accepted in `opts`. 

## Next Steps
After @borkdude eyeballs the above, I'll proceed with a PR for review that includes both code and doc updates.

**Comment by borkdude** [comment]
Eyeballed!
