### ISSUE TITLE
Explore Improving Windows Test Coverage

### ISSUE THREAD

**Issue by lread** [babashka/process#116]
## Problem
Because it has been historically awkward/inconvenient to get all tests also running on Windows, unit test coverage for Windows is for windows-specific behaviours only.

This means our tests aren't exercising babashka/process nearly as much on Windows as we are on macOS and Linux. On Windows we currently run 5 assertions, whereas on macOS/Linux we run 94 assertions.

## Option 1 - carry on as is

Pro: We move faster, no initial work hit, no ongoing work hit.
Con: We have less confidence that babashka/process works as well on Windows.

## Option 2 - make tests more OS-agnostic
Explore using small bb script(s) instead of OS-specific commands to emit/exit whatever/however the test needs.

Pro: tests could be more specific and verify expected outputs
Pro: tests could also be run under Windows
Neutral: Perhaps there are still some OS-specific commands that are worthwhile to run? If so, we could still maintain a small number of OS-specific tests.
Con: Initial work hit, ongoing burden of keeping existing/new tests running under Windows.

## Next Steps
If you are interested in Option 2, I could start exploring to learn how viable this is.
And then if viable, I could make the change.

I could also help with the ongoing Windows test support.

**Comment by borkdude** [comment]
2 seems good to me
