### ISSUE TITLE
dev chore: consider breaking up large deftest forms

### ISSUE THREAD

**Issue by lread** [babashka/process#120]
## Perceived Problem
Babashka process `deftest` forms can contain many `testing` forms.

Because we can only run individual tests at the `deftest` granularity, this makes running specific sets of assertions difficult.

I am finding myself temporarily yanking out `testing` forms to run them individually.

## Proposal
Is it ok with you if I convert most first level `testing` forms to `deftest` forms?

Where there are long `testing` descriptions I'd just leave the `testing` in the broken down `deftest`. Or convert, when appropriate, to use an `is` assertion `msg`.

So this:
```Clojure
(deftest process-test
  (testing "By default process returns string out and err, returning the exit
  code in a delay. Waiting for the process to end happens through realizing the
  delay. Waiting also happens implicitly by not specifying :stream, since
  realizing :out or :err needs the underlying process to finish."
    ....
  (testing "When specifying :out and :err both a non-strings, the process keeps
  running. :in is the stdin of the process to which we can write. Calling close
  on that stream closes stdin, so a program like cat will exit. We wait for the
  process to exit by realizing the exit delay."
   ....
  (testing "copy input from string"
    ....
....
```
Might become this:
```Clojure
(deftest process-wait-realize 
  (testing "By default process returns string out and err, returning the exit
  code in a delay. Waiting for the process to end happens through realizing the
  delay. Waiting also happens implicitly by not specifying :stream, since
  realizing :out or :err needs the underlying process to finish."  
...)

(deftest process-wait-realize-with-stdin 
  (testing "When specifying :out and :err both a non-strings, the process keeps
  running. :in is the stdin of the process to which we can write. Calling close
  on that stream closes stdin, so a program like cat will exit. We wait for the
  process to exit by realizing the exit delay."
...)

(deftest process-copy-input-from-string 
...)
```

I'm also ok with not doing this, if that is your preference, I'm suffering a bit, but not horribly!

Lemme know!

**Comment by borkdude** [comment]
Yep, it's ok with me!

**Comment by lread** [comment]
Notes from our chat: could simply use a REPL to run whatever forms I see fit, but I am working on a Windows VM and tending to verify from the command line. A remote REPL would work I suppose. But I think the split will be convenient moivign forward for cmd line use and will proceed.
