### ISSUE TITLE
Add new `:cmd` `opt` to `exec`

### ISSUE THREAD

**Issue by lread** [babashka/process#125]
## Background
Recently the `:cmd` `opt` was added to `process` functions.
Nice new feature!

## Problem
It would be good, for consistency, to also have `:cmd` `opt` work for `exec` fn.

## Next Steps
I'll follow up with a PR.

**Comment by borkdude** [comment]
Thanks!

**Comment by borkdude** [comment]
This is already fixed with your PR or not?

**Comment by lread** [comment]
No, but I think you maybe fixed it with 3f093b70e114ff8dc318f21dec01a7a2a2fe4fcc.
I'll create a PR to add a test and update the `exec` docstring.
