### ISSUE TITLE
Chore: consider moving to deps.edn only

### ISSUE THREAD

**Issue by lread** [babashka/process#130]
Having both a `deps.edn` and `project.clj` means listing deps twice which can lead to missed bumps.
Example: #129

The last thing I see using `project.clj` is deployment to clojars.
Consider moving to tools.build + deps-deploy for deployment and turfing `project.clj`.

**Comment by borkdude** [comment]
I don't find this an actual problem, I have many projects that deploy through project.clj and I don't mind updating two files. I also enjoy to run tests with `lein test` still.

**Comment by lread** [comment]
Coolio, I shall close.
