### ISSUE TITLE
Question: input and output streams reversed?

### ISSUE THREAD

**Issue by neilclarke** [babashka/process#139]
I might be incorrect, but I'm checking if the stdin is meant to be 'getOutputStream' and stdout 'getInputStream' ? Would have thought it was supposed to be the other way around.

https://github.com/babashka/process/blob/b912d8e15f13ff1b0fd35ea84b8d8c4c899b24b4/src/babashka/process.cljc#L367

Thanks so much for Babashka :)

**Comment by borkdude** [comment]
This is not reversed, the Java naming is just confusing.
