### ISSUE TITLE
Continue doesn't work with (shell)

### ISSUE THREAD

**Issue by crimsonhawk47** [babashka/process#142]
Not able to get this to work on `0.5.21`

```clj
(do (shell {:continue true} "ls foo")
      (println "stuff")) ;; doesn't print
```

**Comment by borkdude** [comment]
Is this with Clojure on the JVM? Can you give a more complete repro? This is what I'm seeing:

```
 $ clj
Clojure 1.12.0-alpha2
user=> (require '[babashka.process :refer [shell]])
nil
(do (shell {:continue true} "ls foo")
      (println "stuff")) ;; doesn't print
ls: foo: No such file or directory
stuff
nil
```

**Comment by crimsonhawk47** [comment]
> Is this with Clojure on the JVM? Can you give a more complete repro? This is what I'm seeing:
> 
> ```
>  $ clj
> Clojure 1.12.0-alpha2
> user=> (require '[babashka.process :refer [shell]])
> nil
> (do (shell {:continue true} "ls foo")
>       (println "stuff")) ;; doesn't print
> ls: foo: No such file or directory
> stuff
> nil
> ```

Yes. I did exactly that and got nothing. I'm on windows with OpenJDK 11.0.14

Exact error in REPL: 

```
; Execution error (IOException) at java.lang.ProcessImpl/create (ProcessImpl.java:-2).
; CreateProcess error=2, The system cannot find the file specified
```

**Comment by crimsonhawk47** [comment]
Ah I see. Does babashka allow you to execute with powershell instead of cmd?

**Comment by borkdude** [comment]
The is no `cmd.exe` involved at all. The binary is directly executed, not via a shell. If you want to execute via a shell, you prefix it yourself:

```
(shell "pwsh ...") ;; whatever the incantation is for powershell
```
