### ISSUE TITLE
clojure.pprint/pprint throws an exception when printing babashka.process.Process

### ISSUE THREAD

**Issue by NoahTheDuke** [babashka/process#143]
Minimal repo:

```
$ cat example.clj
(ns example
  (:require
    [babashka.process :refer [->Process]]
    [clojure.pprint :as pprint]))

(pprint/pprint (->Process :process :exit :in :out :err :prev :cmd))

$ clojure -Sdeps '{:deps {babashka/process {:mvn/version "0.5.21"}}}' -M example.clj
Execution error (IllegalArgumentException) at example/eval3194 (example.clj:6).
Multiple methods in multimethod 'simple-dispatch' match dispatch value: class babashka.process.Process -> interface clojure.lang.IPersistentMap and interface clojure.lang.IDeref, and neither is preferred
```

Thanks so much.

**Comment by borkdude** [comment]
The solution is documented in the README: require `babashka.process.pprint`, this installs a handler for clojure.pprint.

**Comment by NoahTheDuke** [comment]
Ah I missed that. I ran into this when calling `shell` threw exceptions, so I wasn't directly using pprint myself. Is there a reason this isn't implemented by default?

**Comment by borkdude** [comment]
Yes, clojure.pprint isn't loaded automatically because this increases loading time and graalvm binary size.

**Comment by borkdude** [comment]
There one exception though: if you load clojure.pprint BEFORE loading babashka.process, the print-method is installed for you. But not when clojure.pprint isn't already loaded.
