### ISSUE TITLE
`shell` escapes ampersand `&` 

### ISSUE THREAD

**Issue by tastyminerals** [babashka/process#151]
I am trying to setup some common build tasks using `bb.edn` and need to run some shell commands first.
Simple example:
```clojure
{:tasks
 do-stuff {:task (do 
                    (shell "ls -la &")
                    (shell "./gradlew build"))}}

```

If I run `bb do-stuff`, I get
```
ls: &: No such file or directory
Error while executing task: do-stuff
```

Is `shell` prepending `\` to the ampersand?

**Comment by borkdude** [comment]
A common misunderstanding is that `shell` executes bash commands, it doesn't. `foo &` is bash syntax for: run foo in the background. babashka.process simply starts programs, not via shell like bash, zsh or powershell.
To run a program in the background, just use `babashka.process/process`

**Comment by tastyminerals** [comment]
I see, makes sense. Closing.
