### ISSUE TITLE
ci chore: address CircleCI & GitHub Actions macOS change

### ISSUE THREAD

**Issue by lread** [babashka/process#153]
GitHub Actions now maps `macos-latest` to silicon hardware (was formerly intel hardware).

Babashaka/process is currently tested on JDK8 across all OSes, but JDK8 is not available on macOS silicon hardware.

Options:

1. Drop JDK8 testing across all OSes
2. Drop JDK8 testing on macOS only
3. Explicitly choose macOS intel hardware as our runner https://github.com/actions/runner-images?tab=readme-ov-file#available-images

On other projects I've chosen option 2, but option 1 seems reasonable as well. 
What would you like for babashka/process?

I'm happy to follow up with a PR.

**Comment by lread** [comment]
Oh, it looks like macOS Intel hardware is also being phased out at CircleCI.
https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718

**Comment by borkdude** [comment]
yeah we could just drop that one

**Comment by lread** [comment]
Summary from chat with @borkdude
- Since [Clojure 1.12 will still support JDK8](https://github.com/clojure/clojure/blob/ee28f7f06d469b8e4f4eb48521ba51692146e774/changes.md?plain=1#L9), we'll continue to test on JDK8 where we can easily do so
- We'll CI drop testing on JDK8 for macOS only (option 2)
- We discussed testing macOS JDK8 Intel on macOS Silicon using Rosetta, but felt it was not worth it for this lib

**Comment by lread** [comment]
I am working on this in my fork but am still looking for a YAML incantation that works for CircleCI.

**Comment by borkdude** [comment]
What exactly do you mean?

**Comment by lread** [comment]
Yes, a bit brief, was I! 

I have not yet found a combination of `xcode` and m1 `resource_class` that does not return an error like this from CicleCI:

> Resource class macos for macos.m1.medium.gen1, image xcode:14.3 is not available for your project, or is not a valid resource class. This message will often appear if the pricing plan for this project does not support macos use.

I see that you had a similar (but different) [issue](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718/28) a while back.

And others are also confused in more recent days, [circle ci discuss](https://discuss.circleci.com/t/resource-class-macos-for-macos-m1-medium-gen1-image-xcode-15-3-0-is-not-available-for-your-project/51082), [clojurians slack](https://clojurians.slack.com/archives/CJR0NB4MS/p1719211064697289)

I wonder if things will just work after [June 29th when Apple silicon hardware will be the only Apple hardware available at CircleCI](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718/1):

> UPDATE: The sunsetting of Intel resources is now June 28, 2024. After that date, we will only support Apple silicon resources. 
> Starting June 29, 2024 we will only offer Apple silicon-based macOS resources.

**Comment by lread** [comment]
An alternative: I can drop JDK8 on macOS on CircleCI and come back to see the state of macOS silicon on CircleCI on June 29th. We don't currently specify a macOS `resource_class`; the default might just magically change to silicon and everything might work.

**Comment by lread** [comment]
@borkdude Is it June 29th. I pushed an empty commit on my bb process fork to test CircleCI macOS behaviour. Glad to report that it seems to be [automagically switching to macOS m1](https://app.circleci.com/pipelines/github/lread/process?branch=lread-check-m1-support):

![image](https://github.com/babashka/process/assets/967328/5de2e801-6840-4d14-aa30-b5fdf4efb7ed)

And from Setup JDK step output some `aarch64` evidence:
```
Installing graalvm_community 22 for macos aarch64
```

The rollout might be a bit rough, as my macOS jobs are queueing and running one at a time and CircleCI cache saving seems to be taking eons. But hopefully things will smooth out.
