### ISSUE TITLE
test: run against clojure 1.12

### ISSUE THREAD

**Issue by lread** [babashka/process#159]
Since Clojure 1.12 is now in beta, it probably is a good time to start testing against it.

I will follow up with a PR unless you object.

Minor: We should also be testing against clj 1.11.3 (current) but are testing against 1.11.1. I will also address this in the same PR.

**Comment by borkdude** [comment]
I'm fairly confident that newer Clojure versions won't impact bb.process so it seems a bit redundant to me

**Comment by borkdude** [comment]
But if you insist!

**Comment by lread** [comment]
You are probably right. 

But you will probably test against clojure 1.12 when it is released, yes? You are currently testing against 1.9, 1.10, and 1.11. Will you stop testing against those versions or reduce the versions you test against?

**Comment by lread** [comment]
> But if you insist!

This is your project, I don't want to make changes you disagree with.
I certainly don't insist, but I think it is probably a good idea.

**Comment by borkdude** [comment]
Since the inception of most of my OSS libs I've been testing back to 1.9. As a rule of thumb (I think I had this from Alex) one major version before the last release and at the time that was 1.9 + 1.10

**Comment by borkdude** [comment]
> I certainly don't insist, but I think it is probably a good idea.

Let's go ahead then
