### ISSUE TITLE
process fails to shell out on Windows when there is a double quoted dir in PATH

### ISSUE THREAD

**Issue by borkdude** [babashka/process#168]
See https://github.com/babashka/babashka/issues/1726

cc @lread: we changed something to `-process-resolver` in process to make it call `fs/which`, but `fs/which` fails when there is a quoted path in PATH, on Windows which is why somebody in the above mentioned issue had a script that didn't run anymore when upgrading bb.

Not sure what's the best thing to do. Perhaps making `fs/which` more robust or so... not sure yet.

**Comment by lread** [comment]
Sacré Windows! My inclination would be to update `fs/which` to understand the possibility of quoted paths in PATH on Windows.

Currently, the only other idea I can think of is spawning out and asking a Windows shell to search the PATH. But even if that could work, it would have its own can of worms.

Lemme know if you help with this - or want to explore other ideas.

**Comment by borkdude** [comment]
Perhaps we should just treat it as an error and do nothing:

https://serverfault.com/a/349216/77377

**Comment by lread** [comment]
Ah. I like your idea better than mine! 
We now know the symptom of the problem.
The solution is to not to use quoted paths in PATH on Windows; it is problematic in general.
