### ISSUE TITLE
Background processes started from bb tasks on Windows die on script exit

### ISSUE THREAD

**Issue by timgilbert** [babashka/process#169]
This is kind of a weird case, and I'm not 100% sure whether it's an issue with the library, something weird in my code, or a peculiarity of babashka tasks. 

I'm trying to write a babashka script that can run a Windows process in the background, so that it outlives the script. I'm specifically running `tsh db proxy`, which is a [teleport ](https://goteleport.com/docs/reference/cli/tsh/#tsh-proxy-db) command that opens up a tunnel between two machines so that a database connection can be established.

From a powershell prompt I can run this, and it works successfully; the running `tsh` command is in the background and it outlives the powershell session and the terminal session that it's running in:

```powershell
> powershell Start-Process -WindowStyle Hidden tsh -ArgumentList "proxy","db","my-server","--db-user","editor","--port","1234","--tunnel"

> ps tsh
Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    234      18    40692      59512       0.02  43536   1 tsh
```

From the REPL, I can run this, and the command remains in memory and outlives the REPL (running a babashka repl from IntelliJ):

```clojure
(pprint (shell {:out :string :err :string} "powershell Start-Process -WindowStyle Hidden tsh -ArgumentList 'proxy,db,my-server,--db-user,editor,--port,1234,--tunnel'"))
{:proc
 #object[java.lang.ProcessImpl 0x627f4786 "Process[pid=39800, exitValue=0]"],
 :exit 0,
 :in
 #object[java.lang.ProcessBuilder$NullOutputStream 0x569b4177 "java.lang.ProcessBuilder$NullOutputStream@569b4177"],
 :out "",
 :err "",
 :prev nil,
 :cmd
 ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
  "Start-Process"
  "-WindowStyle"
  "Hidden"
  "tsh"
  "-ArgumentList"
  "proxy,db,my-server,--db-user,editor,--port,1234,--tunnel"]}
```

...but when I try to run this from a babaska task, the command seems to succeed, but the `tsh` process is not running after the `bb` executable exits:

```clojure
;; bb.edn
{:tasks {start-tsh {:task (exec 'skydb.proxy/start-tsh)}}}

;; skydb.proxy
(defn start-tsh [_]
  (let [ps (shell
             {:out :string :err :string}
             "powershell Start-Process -WindowStyle Hidden tsh -ArgumentList 'proxy,db,my-server,--db-user,editor,--port,1234,--tunnel'")]
    (pprint ps)
    ps))
```

Running this as `bb run start-tsh` gives me the same output as the REPL session, but the `tsh` command is no longer running.

```powershell
> bb run start-tsh
{:proc
 #object[java.lang.ProcessImpl 0x6008dc33 "Process[pid=32716, exitValue=0]"],
 :exit 0,
 :in
 #object[java.lang.ProcessBuilder$NullOutputStream 0x569b4177 "java.lang.ProcessBuilder$NullOutputStream@569b4177"],
 :out "",
 :err "",
 :prev nil,
 :cmd
 ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
  "Start-Process"
  "-WindowStyle"
  "Hidden"
  "tsh"
  "-ArgumentList"
  "proxy,db,my-server,--db-user,editor,--port,1234,--tunnel"]}

> ps tsh
ps : Cannot find a process with the name "tsh". Verify the process name and call the cmdlet again. [...]
```

I'm a bit baffled by this (and also not crazy familiar with Windows process control). Is there anything in the babashka task runner that might account for the background task dying after the script exits?

**Comment by timgilbert** [comment]
Oh, as a note, I have tried this with PowerShell versions 5.1 and 7.4 and I see the same behavior on both.

**Comment by borkdude** [comment]
> I'm trying to write a babashka script that can run a Windows process in the background, so that it outlives the script. 

If you want a process to outlive the bb process, it's usually best to use `(babashka.process/process ...)` rather than `shell`.
Can you try this?

**Comment by timgilbert** [comment]
I think I'm hitting a separate unrelated bug while messing around with `(process)`, which is that if I use an `:out :write` option I get an error invoking powershell. This happens in `(shell)` too:

```
(shell {:out :write :err :string} "powershell echo hello")

----- Error --------------------------------------------------------------------
Type:     java.io.IOException
Message:  Cannot run program "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe":  (The system cannot find the file specified)
----- Context ------------------------------------------------------------------
```

The path it's attempting to use is the correct location, and the same invocation works file with `:out :string`. I can open a new issue to track this if you'd like.

**Comment by borkdude** [comment]
When using `:out :write` you must also supply `:out-file` with the file to write to:

https://github.com/babashka/process?tab=readme-ov-file#redirecting-output-to-a-file

**Comment by timgilbert** [comment]
I created this little repo to try to demonstrate the problem and work on a fix: https://github.com/timgilbert/bbbackground

(To be clear, I still suspect this bug is more about my code than babashka, but if I can figure it out I can at least add a wiki page or something.)

**Comment by borkdude** [comment]
I suspect there's little that bb.process can do about this if the same stuff happens with ProcessBuilder directly, so I'm closing this until we have evidence it's an issue with this lib.

**Comment by timgilbert** [comment]
I agree, thanks @borkdude! I'll add a note to this ticket with more information if I do get it figured out, just for the sake of future developers.
