### ISSUE TITLE
Support :dir on $-macro

### ISSUE THREAD

**Issue by MrGung** [babashka/process#33]
Now I am doing

` (with-meta ($ "cmd.exe" "/C" "dir" "/S" "/OD" "/B" "/AD" ) {:dir root})`

but the value of `root` is not considered.

`(process '["cmd.exe" "/C" "dir" "/S" "/OD" "/B" "/AD"] {:dir root})`

works as expected.

**Comment by borkdude** [comment]
@MrGung The way this works is that you need to pass the metadata on the ls form, before it is evaluated:

```
user=> (def ls ^{:dir "/tmp"} ($ ls))
#'user/ls
user=> (-> ls :out slurp str/split-lines first)
"200mb.zip"
```

When you write:

```
(with-meta ($ ls) ...)
```
what happens is that `($ ls)` gets evaluated before metadata is added, so that doesn't work.

**Comment by MrGung** [comment]
Thought `with-meta` is a macro and didn't look it up... :-(

Thanks for pointing that out!

**Comment by borkdude** [comment]
No problem!
