### ISSUE TITLE
How can it be installed with lein

### ISSUE THREAD

**Issue by tami5** [babashka/process#34]
Hey everyone, I wonder how I can use this awesome lib with my clojure project and lein, I tried voom but didn't get anywhere.

Thanks

**Comment by borkdude** [comment]
Currently you can't. Let me make a release to clojars.

**Comment by tami5** [comment]
:heart: :heart: . Also @borkdude I need your advice, on using babashka. I'm not sure how I can build a project based on it and then compile it down to a single binary. For now I took dad's configuration management tool approach. Here's a link to my repo to get a general idea of what I'm trying to build. Currently it uses janet, https://github.com/tami5/dotenv.

Thanks a lot

**Comment by borkdude** [comment]
@tami5 https://clojars.org/babashka/process

**Comment by borkdude** [comment]
>  I'm not sure how I can build a project based on it and then compile it down to a single binary.

Why do you want to do this? I'm not sure if I understand the use case. You could in theory compile a fork of babashka that executes a script on startup, but if you're going down that road, you might just as well create your own GraalVM based project.

**Comment by borkdude** [comment]
@tami5 I have a sort of similar tool here: 

https://github.com/borkdude/glam

which is using its own GraalVM-based binary to install deps. Maybe this is closer to what you want?

**Comment by borkdude** [comment]
An alternative is to use an uberscript or uberjar with your scripts and resources:

https://github.com/borkdude/babashka#uberscript
https://github.com/borkdude/babashka#uberjar

**Comment by tami5** [comment]
> Why do you want to do this? I'm not sure if I understand the use case. You could in theory compile a fork of babashka that executes a script on startup, but if you're going down that road, you might just as well create your own GraalVM based project.

Okay that clear a misconception I had, I just made babashka=complied clojure. :D Thanks for clarifying that out, I was going round and round in my head.


> @tami5 I have a sort of similar tool here:
> 
> https://github.com/borkdude/glam
> 
> which is using its own GraalVM-based binary to install deps. Maybe this is closer to what you want?

Yes, very good. Oh wow it has one of the key feature I want in my tool. Very interesting design. Thanks, it will help a lot.

My original question
