### ISSUE TITLE
Incorrect expansion when using = in the arguments for some script

### ISSUE THREAD

**Issue by wandersoncferreira** [babashka/process#37]
Hello @borkdude I just happen to notice something odd when using `$` to command a docker build process. I have the following code:

```clojure
(def base-build-image-name "my-image")
(def jarfile "target/app.jar")

($ docker build
    -t ~base-build-image-name
    --build-arg jarfile=~jarfile
    -f resources/Dockerfile .)
```

However, the expansion I see in the terminal after executing this command is the following:

`docker build -t my-image --build-arg jarfile= target/app.jar -f resources/Dockerfile .`

If you look closely there is a space after the `=` sign. I started debugging this and I have a possible fix that I would like to discuss. Looks like `$` macro produces a list of symbols to be manipulated during the process and in the end we get the following vector:

`["docker" "build" "-t" "my-image-name" "--build-arg" "jarfile=" "target/app.jar" "-f" "resources/Dockerfile" "."]`

The issue here is that "jarfile=target/app.jar" should be together. I think this is kind of general for these situations and instead of messing around the other parts of the code I created a function to be executed after this operation https://github.com/babashka/process/blob/ac1219508857d4b3106e5a7999a3573c61c7aa63/src/babashka/process.clj#L115 which will scan the vector above and if it encounters a parameter with a "=" sign it will merge the next element into it.

What you think about this? I couldn't came up with more examples where this would be useful too.

**Comment by wandersoncferreira** [comment]
A workaround would be to do the following:

```clojure
($ docker build
  -t ~base-build-image-name
  --build-arg ~(str "jarfile=" jarfile)
  -f resources-dos/Dockerfile .)
```

**Comment by borkdude** [comment]
That would be the preferred solution. `$` is a macro which looks at its arguments in the following way: `~x` expands to `(clojure.core/unquote x)` so if an argument is a list which starts with `clojure.core/unquote` then it will do interpolation. In other cases it will just leave the argument as is.

**Comment by wandersoncferreira** [comment]
Cool, I will close the issue. thanks
