### ISSUE TITLE
Support for PIPE redirection

### ISSUE THREAD

**Issue by SevereOverfl0w** [babashka/process#49]
https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/ProcessBuilder.Redirect.html#PIPE is useful as it allows you to close stdin/stdout.  In my case I've started a REPL, and I can cause a "clean shutdown" by closing the process stdin.  I can't do that with inherit though.

**Comment by borkdude** [comment]
Isn't this already the default - i.e. when you don't provide any options, this is the thing it uses?

**Comment by SevereOverfl0w** [comment]
You're right, this is even in the javdocs!

> a destination for standard output and standard error. By default, the subprocess writes standard output and standard error to pipes

Thanks!  I can remove some code now.  The best kind of action.
