### ISSUE TITLE
deref with timeout

### ISSUE THREAD

**Issue by SevereOverfl0w** [babashka/process#50]
So I can wait for a process to die naturally or destroy it `(or (deref process 5000 nil) (bb.process/destroy process))`.

Could be implemented using https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Process.html#waitFor(long,java.util.concurrent.TimeUnit) ?

**Comment by borkdude** [comment]
@SevereOverfl0w `IDeref`, the interface that process records implement, does not support the timeout arity.
But I guess we could also implement `clojure.lang.IBlockingDeref` to support that use case.
Note that you can also grab the process with `:proc` and call `waitFor` yourself, although I think it's good to support what you wrote above.

**Comment by borkdude** [comment]
```
$ bb -e '(.waitFor (:proc (babashka.process/process ["clojure" "-M" "-e" "(Thread/sleep 10000)"])) 1000 java.util.concurrent.TimeUnit/MILLISECONDS)'
false
```
