### ISSUE TITLE
'$' macro does not work in '->'

### ISSUE THREAD

**Issue by carlzhc** [babashka/process#52]
It seems `$` macro only work in one command execution, not pipelined (tested in bb).
```
user=> (-> ($ echo hello) ($ sed p) deref :out slurp println)
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No method in multimethod 'do-copy' for dispatch value: [java.lang.ProcessImpl$ProcessPipeInputStream java.lang.ProcessImpl$ProcessPipeInputStream] [at <repl>:13:1]

user=> (-> (process '[echo hello]) (process '[sed p]) deref :out slurp println)
hello
hello
```

**Comment by carlzhc** [comment]
Seems `$` does not work in piping at all.

**Comment by borkdude** [comment]
@carlzhc Should it? We can try to fix it. But since you closed this, you might not be interested in it anymore?

**Comment by borkdude** [comment]
I think it was supposed to work, but something may have been broken recently when we added support for passing options in the first position instead of via metadata..

https://github.com/babashka/process/blob/eb035138aacf94f0bd635f650dbc639b0a4a7328/src/babashka/process.cljc#L354

**Comment by borkdude** [comment]
You know what, I undocumented $ and made it deprecated. I think it's more trouble/magic than it's worth.

**Comment by carlzhc** [comment]
Actually, I found the '$' does not support piping at all.
The second argument is supposed to be an option map to the command,  not a previous command record as in 'process'.

**Comment by borkdude** [comment]
I've looked into this more and the fix wasn't so difficult. I decided to undeprecate `$`.
