### ISSUE TITLE
Default to streams instead of strings

### ISSUE THREAD

**Issue by borkdude** [babashka/process#7]
This is less opinionated and same as the Java API.

**Comment by grzm** [comment]
I came across babashka.process when looking for examples of reading stdout/stderr before a process has completed. As such, `:wait false` is the case I'm interested in, and the current `:err`/`:out` defaults prevent `:wait false` being used independently of also specifying, say,  `{:err :stream, :out :stream}`. Defaulting to streams make this easier for my particular use case. Why I'd reach for ProcessBuilder as opposed to clojure.java.shell would be the general case of

```clojure
(let [proc (.start pb)]
  {:proc proc
   :err (.getErrorStream proc)
   :out (.getInputStream proc)
   :exit (future (.waitFor proc))})
```

That said, I don't know if this is the most convenient for more common, synchronous cases (`{:wait true}`), situations that are more similar to when one might want something nearly like `clojure.java.shell/sh`: string results, exit codes as integers, not futures. It's also a bit off having different return values based on the value of `:wait`.

It's a common pattern to have async and sync api interfaces. This seems similar. Perhaps two different (named) flavors of `process` (`proc` and `process`?)? One for the general case returning something like above (`{:wait false}`, returning streams and `:exit` as a future), and one with `{:wait true}`, returning `:out/:err` strings by default, and `:exit` as an int. If you're going to be reading results as they stream in, you're going to want to wait and deal with streams anyway, and if you're looking for synchronous behavior, you probably don't want to deal with streams by default.

There is the option of changing what's returned for `:out` and `:err` depending on the value of `:wait` (without specifying them explicitly), but I think that would result in surprising behavior, as opposed to having separate functions.

**Comment by borkdude** [comment]
Good points. I had similar thoughts and hence warnings about breaking changes that might happen. 

>  If you're going to be reading results as they stream in, you're going to want to wait and deal with streams anyway

If you're reading in a stream, you don't necessarily want to wait, especially not if the next process is reading your output stream, if the output can be "inifite".

**Comment by grzm** [comment]
💯 That's clearly what I wrote, and exactly the opposite of what I meant. I've fired my copy editor. Cheers!

**Comment by borkdude** [comment]
Process now defaults to streams. In fact, there is no way to get strings unless you use `slurp`.
