### ISSUE TITLE
Support pretty printing of babashka.process.Process

### ISSUE THREAD

**Issue by ivarref** [babashka/process#94]
Hi

and thanks for all your great work and great projects!

I've noticed a (for me) confusing error message:

```clojure
(try
    (as-> ^{:out :string :err :string} ($ ls -l asdf) v
          (check v))
    (catch Exception e
      (pprint/pprint (ex-data e))))
```

will output:
```
Multiple methods in multimethod 'simple-dispatch' match dispatch value: class babashka.process.Process -> interface clojure.lang.IDeref and interface clojure.lang.IPersistentMap, and neither is preferred
```
i.e. the pretty printing failed. (At least if the file `asdf` does not exist.)

This solves the problem:
```clojure
(defmethod clojure.pprint/simple-dispatch babashka.process.Process
  [proc]
  (pr proc))
```
I'm sure the solution can be improved though.

Hope it's possible to fix this as it has both bitten and confused me a few times.

Thanks and kind regards.

**Comment by borkdude** [comment]
The solution is here: https://github.com/babashka/process#clojurepprint

**Comment by ivarref** [comment]
Thanks @borkdude for a quick reply!

Is there any particular reason why the `babashka.process.pprint` namespace is not required by `babashka.process`?

**Comment by borkdude** [comment]
Yes, to not require `clojure.pprint` pre-emptively since clojure.pprint can have a negative impact on graalvm image size.

**Comment by ivarref** [comment]
Aha OK thanks :+1:
